# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
